const express = require('express')
const authRoute = require('./v1/auth.route')
const userRoute = require('./v1/users.route')
const movieRoute = require('./v1/movie.route')
const cinemaRoute = require('./v1/cinema.route')
const bookingRoute = require('./v1/booking.route')
const dirRoute = require('./v1/director.route')
const actorRoute = require('./v1/actor.route')
const commentRoute = require('./v1/comment.route')
const ageTypeRoute = require('./v1/age.route')
const genresRoute = require('./v1/genres.route')
const tagsRoute = require('./v1/tags.route')
const rootRoute = express.Router()

rootRoute.use('/v1/auth', authRoute)
rootRoute.use('/v1/users', userRoute)
rootRoute.use('/v1/movies', movieRoute)
rootRoute.use('/v1/cinema', cinemaRoute)
rootRoute.use('/v1/tickets', bookingRoute)
rootRoute.use('/v1/directors', dirRoute)
rootRoute.use('/v1/actors', actorRoute)
rootRoute.use('/v1/comments', commentRoute)
rootRoute.use('/v1/ages', ageTypeRoute)
rootRoute.use('/v1/genres', genresRoute)
rootRoute.use('/v1/tags', tagsRoute)

module.exports = rootRoute
