const movieController = require('../../controllers/movie.controller')
const { verifyAdmin, verifyToken } = require('../../middlewares/users.middleware')
const express = require('express')
const movieRoute = express.Router()

movieRoute.get('/banner', movieController.getAllBanner)
movieRoute.get('/search', movieController.searchMovie)
movieRoute.get('/all-movie', movieController.getAllMovie)
movieRoute.get('/pagination', movieController.getPaginationListOfMovie)
movieRoute.get('/users-like', verifyAdmin, movieController.getUsersLikeMovie)
movieRoute.get('/users-rating', verifyAdmin, movieController.getUsersRatingMovie)
movieRoute.get('/paging-movie-by-date', movieController.getMovieByDate)
movieRoute.post('/upload-poster', movieController.uploadPoster)
movieRoute.post('/insert', verifyAdmin, movieController.insertMovie)
movieRoute.put('/update', verifyAdmin, movieController.updateMovie)
movieRoute.delete('/delete', verifyAdmin, movieController.deleteMovie)
movieRoute.get('/directors', movieController.getListDirector)
movieRoute.get('/actors', movieController.getListActor)
movieRoute.get('/genres', movieController.getListGenres)
movieRoute.get('/tags', movieController.getListTags)

module.exports = movieRoute
