const express = require('express')
const userController = require('../../controllers/users.controller')
const { verifyAdmin, verifyToken } = require('../../middlewares/users.middleware')
const userRoute = express.Router()

userRoute.get('/all-users', verifyAdmin, userController.getAllUsers)
userRoute.post('/test-token', userController.testToken)
userRoute.post('/refresh-token', userController.refreshToken)
userRoute.get('/forgot-password', userController.forgotPassword)
userRoute.put('/reset-password', userController.resetPassword)
userRoute.get('/user-types', verifyToken, userController.getAllUserType)
userRoute.get('/pagination', verifyAdmin, userController.getPaginationListOfUser)
userRoute.get('/search', verifyAdmin, userController.searchUser)
userRoute.get('/search-paging', verifyAdmin, userController.searchUserPagination)
userRoute.get('/profile', userController.getProfileUser)
userRoute.get('/account', userController.getInfoUser)
userRoute.post('/insert', userController.insertUser)
userRoute.put('/update', userController.updateUser)
userRoute.put('/update-admin', userController.updateUserByAdmin)
userRoute.post('/upload-avatar', userController.uploadAvatar)
userRoute.delete('/delete', userController.deleteUser)
userRoute.post('/like', userController.likeMovie)
userRoute.post('/unlike', userController.unlikeMovie)
userRoute.post('/rating', userController.ratingMovie)
userRoute.get('/movie-favorite', userController.getAllMovieFavorite)
userRoute.get('/movie-rating', userController.getAllMovieRating)

module.exports = userRoute
